### PR TITLE
 Optimise codebase according to latest pythonic code style 

### LINKED ISSUE #127: Type annotate the codebase.

### PR DESCRIPTION
**Pull request by Agent-Hellboy**
Consider this as an WIP PR, I will try to cover more methods as I need to solve some circular dependencies, I am thinking of using mypy for type checking, I can see that unittest are missing for base.py, maybe i will add those as well. Or if you want i can create a new issue named `increase code coverage`

I have made one extra change of converting all instances of `string formatting using .format()` to f string.

### CODE REVIEW

**Comment by pri22296** [comment]
I agree with everything you proposed. I would prefer if we can have the f-string change in a separate PR with it's own issue. same with the other changes like including tests, integration with mypy. Will allow smaller changes to be checked in without getting blocked by unrelated blockers.

For type annotations, It would be easier to have a single issue tracking other child issues, wherein you can have smaller PR's for maybe each module at a time. Would make reviews easier.

**Comment by Agent-Hellboy** [comment]
fixes

**Comment by pri22296** [comment]
@Agent-Hellboy Is this PR still WIP? If yes, can you then add a [WIP] tag before PR's title. If no, let me know and I'll approve this.

**Comment by pri22296** [comment]
@Agent-Hellboy Is this PR still WIP?

**Comment by Agent-Hellboy** [comment]
This is final

**Review by pri22296 — APPROVED** [review]

**Pull request merged**
