### PR TITLE
62 - Create import and export from json file

### PR DESCRIPTION
**Pull request by dinko-pehar**
I have created import and export to json file #62 . I have also included thorough testing for functionality.

Exporting to json supports several configuration that comply with `json.dump` function.

Example:

```
table = BeautifulTable(max_width)
table.column_headers = ["name", "rank", "gender"]
table.append_row(["Jacob", 1, "boy"])
table.append_row(["Isabella", 1, "girl"])
table.append_row(["Ethan", 2, "boy"])
table.append_row(["Sophia", 2, "girl"])
table.append_row(["Michael", 3, "boy"])
```

JSON file:

```
[
    {
        "name": "Jacob",
        "rank": 1,
        "gender": "boy"
    },
    {
        "name": "Isabella",
        "rank": 1,
        "gender": "girl"
    },
    {
        "name": "Ethan",
        "rank": 2,
        "gender": "boy"
    },
    {
        "name": "Sophia",
        "rank": 2,
        "gender": "girl"
    },
    {
        "name": "Michael",
        "rank": 3,
        "gender": "boy"
    }
]
```

---

Some things to note:
- This functionality doesn't support exporting Subtables. (_Can be added if needed_)
- `table.column_headers` should not contain empty names, since JSON is name/value pairs of data.
- `to_json` method receives `indent` argument which is equivalent to argument `indent` of `json.dump`. I'm not completely sure how to state that this parameter can be `int` or `str` or `None` in _Numpy docstring_. Check indent argument at https://docs.python.org/3.7/library/json.html#json.dump .

If you need me to expand, improve or reduce functionality, I'm happy to comply with guidelines.

### CODE REVIEW

**Comment by pri22296** [comment]
Sorry for the late response. I've been a little busy. Seeing your idea about the `indent` parameter, I think it would be better if we just provide a method like `to_obj` or something like that. That way, user is free to take advantage of all the options the json module provides. What do  you think about that?
Also about headers being empty, yeah that's an issue. Currently headers can be empty or even duplicate which will also cause an issue here. I plan to make headers unique as the current approach provides no benefits.

**Comment by dinko-pehar** [comment]
Thank you for your response, it's never late :smile_cat: .

I think exporting _Beautiful Table_ to object which is JSON serializable is better approach. In that way, users can rely on `json` module and use all of it's functionality as they please.
But I'm not sure will it produce inconsistent API in _Beautiful Table_. For example, for CSV, we have `to_csv` and `from_csv`. Now, if we replace `to_json` with `to_obj`, we will have `to_obj` and `from_json`. Is this good approach ? 
Maybe we should provide users who use _Beautiful Table_ easier way of thinking in patterns; use `to_json`, `to_csv`, `to_html`, `to_yaml` `to_X` then different kind of similar patterns. Also, users may want to use functionalities without heavy thinking about them (_"Just export it to JSON any way you want without me doing additional work"_).

---

My idea is to add `to_obj` as **property** and change `to_json` to use it internally. In that way, users can export object as dictionary or export to json, any way is valid.  But I leave it up to you to decide. :thought_balloon:

**Comment by pri22296** [comment]
Upon further consideration, why would a user need a JSON representation? If it is only for serialization purpose, then I think, we should export not just the data but also any custom  styling, alignment, etc  which the user has applied. You can always do `list(table)` to get the data so a separate method isn't required for exporting just the data.

**Comment by dinko-pehar** [comment]
Sorry for late response.

I tried to contribute with `json` import and export, but your guidelines weren't clear really for me at the time. I didn't understand you completly and stopped working on this feature. If I see something interesting in issues, I'll try to contribute. I'm closing this one as unfinished for now.

**Pull request closed without merging**
